### ISSUE TITLE
Question about 16384

### ISSUE THREAD

**Issue by madclouds** [jamesalvarez/iosCoreAudioPlayer#2]
Hi James,

First, thanks for putting this sample app together.  It has really helped me with my implementation integrating with some older frameworks.  

I hope you don't mind me opening a ticket, but I had a question about this line:

```UInt32 framesToRead = (16384 < framesLeftToRead) ? framesLeftToRead : 16384;```

In context: https://github.com/jamesalvarez/iosCoreAudioPlayer/blob/cd2024e08f5e2a19b455ac090feb858fc667cf7f/CoreAudioPlayer/CoreAudioPlayer/SoundController.c#L180

When running in the simulator, this code worked great, but once I tried to deploy it to device, it was crashing.  I chased it down to where my `framesLeftToRead` was small due to the small sample files I am using (like `8164`), and therefore `framesToRead` was always being set to 16384.  I'm not quite sure what the significance of this value is?  I was able to work around it by inverting the conditional so that `framesLeftToRead` was always the smaller value from my sample.

I believe my app was crashing because the device uses different data type representations between MacOS simulator and iOS devices.  And for some reason, that `16384` doesn't play nice on device.

I was hoping you could shed some light on what's going on, or why I couldn't get this to run on device?

Again, I greatly appreciate you blog post explaining this code, and the repo to back it up!

**Comment by jamesalvarez** [comment]
I think it's a typo in my code, it should be:
 UInt32 framesToRead = (framesLeftToRead < 16384) ? framesLeftToRead : 16384; 
Strange its not crashing on the device!


16384 was taken from some other source code I found, its 2 the power of 17 so must be some sort of memory chunk...

**Comment by madclouds** [comment]
Much appreciated James!
